services:
  api:
    build:
      context: .
    container_name: gin_api
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./:/go/src/app

  db:
    image: postgres:17
    container_name: gin_api_db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
