services:
  testapp:
    build:
      context: .
      target: builder
    command: go test -v ./...
    container_name: golang_playground_testapp
    environment:
      # Set to "release" to avoid spamming the console.
      GIN_MODE: release
    depends_on:
      - testdb
    volumes:
      - ./:/go/src/app

  testdb:
    image: postgres:17
    container_name: golang_playground_testdb
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
